spring:
  rabbitmq:
    addresses: 192.168.17.130:5672
    username: test
    password: test
    virtual-host: test
    connection-timeout: 15000
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /
  port: 8001
