spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.17.130:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: 123456
  rabbitmq:
    addresses: 192.168.17.130:5672
    username: test
    password: test
    virtual-host: test
    connection-timeout: 15000
    publisher-confirms: true #手动确认
    publisher-returns: true #手动确认
    template:
      mandatory: true #手动确认
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /
  port: 8001
mybatis:
  type-aliases-package: com.pcgrw.sbrabbit.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    tk:
      mybatis: TRACE
